import Foundation

/// The shell script Claude Code's `statusLine` feature invokes on every
/// update. Parses each provider's cache file with `grep`/`cut` rather than
/// `jq` or `python3` — neither is guaranteed to be on a user's `PATH` —
/// since each cache is a small, flat, known-shape JSON object. Reads all
/// three providers' caches (Claude, Codex, Gemini), not just Claude's own,
/// since that's the whole point of a multi-provider switcher — Claude Code
/// already puts the active session's own rate limit in its stdin JSON, so
/// showing only Claude here would add nothing.
public enum StatuslineScriptGenerator {
    public static func script(cacheDirectory: URL) -> String {
        let providers: [Provider] = [.anthropic, .openai, .gemini]
        let reads = providers.map { provider -> String in
            let path = StatuslineCache.defaultFileURL(for: provider, in: cacheDirectory).path
            return """
            if [ -f "\(path)" ]; then
                JSON=$(cat "\(path)")
                EMAIL=$(echo "$JSON" | grep -o '"email":"[^"]*"' | cut -d'"' -f4)
                SESSION=$(echo "$JSON" | grep -o '"sessionPercent":[0-9.]*' | cut -d: -f2)
                WEEKLY=$(echo "$JSON" | grep -o '"weeklyPercent":[0-9.]*' | cut -d: -f2)
                PARTS="$PARTS \(provider.displayName) $SESSION%/5h $WEEKLY%/week ($EMAIL) |"
            fi
            """
        }.joined(separator: "\n")

        return """
        #!/bin/sh
        # Generated by FuelSwitch AI. Re-run "Install" in FuelSwitch AI's
        # Settings after a FuelSwitch AI update if this stops working.
        PARTS=""
        \(reads)
        if [ -z "$PARTS" ]; then
            echo "FuelSwitch: no data yet"
            exit 0
        fi
        printf 'FuelSwitch%s\\n' "${PARTS%|}"
        """
    }
}
